[Sascha Spors](https://orcid.org/0000-0001-7225-9992),
Professorship Signal Theory and Digital Signal Processing,
[Institute of Communications Engineering (INT)](https://www.int.uni-rostock.de/),
Faculty of Computer Science and Electrical Engineering (IEF),
[University of Rostock, Germany](https://www.uni-rostock.de/en/)

# Tutorial Signals and Systems (Signal- und Systemtheorie)

Summer Semester 2022 (Bachelor Course #24015)

- lecture: https://github.com/spatialaudio/signals-and-systems-lecture
- tutorial: https://github.com/spatialaudio/signals-and-systems-exercises

Feel free to contact lecturer [frank.schultz@uni-rostock.de](https://orcid.org/0000-0002-3010-0294)

02A5968B56 corresponding to Appendix in sig_sys_ex_11.tex

## Circular Convolution  by Circular Matrix Multiplication vs. DFT / IDFT

In [1]:
import numpy as np
from numpy.linalg import eig
from numpy.fft import fft, ifft

In [2]:
# set up two circular matrices
X = np.array([
    [-1, 4, 2], 
    [2, -1, 4], 
    [4, 2, -1]])

H = np.array([
    [3, 5, 1], 
    [1, 3, 5], 
    [5, 1, 3]])

In [3]:
# get Fourier matrix
N = X.shape[0]
k = np.arange(N)
K = np.outer(k, k)
F = np.exp(+1j*2*np.pi/N * K)  # orthonormal
Fn = F / np.sqrt(N)  # unitary

In [4]:
# get 1st col as this shall represent our discrete-time signals
xk = X[:, 0]
hk = H[:, 0]

In [5]:
# check DFT / IDFT pair
xmu = F.conj().T @ xk  # DFT
xkr = 1/N * F @ xmu  # IDFT
print(np.allclose(xk, xkr))

True


We even don't need the transpose, it's working just with the conjugate-complex, see Fourier matrix properties in [fourier_matrix_39AF81A22A.ipynb](fourier_matrix_39AF81A22A.ipynb)

In [6]:
# check DFT / IDFT pair
xmu = F.conj() @ xk  # DFT
xkr = 1/N * F @ xmu  # IDFT
print(np.allclose(xk, xkr))

True


In [7]:
# check DFT / IDFT pair with the unitary F
xmu = Fn.conj() @ xk  # DFT
xkr = Fn @ xmu  # IDFT
print(np.allclose(xk, xkr))

True


cyclic convolution by circular matrix multiplication

In [8]:
Y = X @ H
print(Y)
Y = H @ X  # conv is commutative
print(Y)

[[11  9 25]
 [25 11  9]
 [ 9 25 11]]
[[11  9 25]
 [25 11  9]
 [ 9 25 11]]


now check the underlying eigenwert problem

In [9]:
xmu = F.conj().T @ xk
print(xmu)  # result are eigvals of circ matrix X
wx, vx = eig(X)
print(wx)  # these might be sorted differently
print(np.allclose(xmu, wx))  # but in this example on my computer we get True

[ 5.+0.j         -4.+1.73205081j -4.-1.73205081j]
[ 5.+0.j         -4.+1.73205081j -4.-1.73205081j]
True


In [10]:
hmu = F.conj().T @ hk
print(hmu)  # result are eigvals of circ matrix H
wh, vh= eig(H)
print(wh)  # these might be sorted differently
print(np.allclose(hmu, wh))  # but in this example on my computer we get True

[ 9.00000000e+00+0.j         -2.22044605e-15+3.46410162j
  3.55271368e-15-3.46410162j]
[ 9.0000000e+00+0.j         -4.4408921e-16+3.46410162j
 -4.4408921e-16-3.46410162j]
True


In [11]:
# we multiply spectral coeff (i.e. eigvals of X and H) element-wise
# and do the IDFT via Fourier matrix
y = 1/N * F @ (xmu * hmu)

# this shall be the same as
# cyclic conv via fft() / ifft()
y1 = ifft(fft(X[:, 0]) * fft(H[:, 0]))

print('Y =\n', Y)
print('y = Y[:,0] =\n', np.real_if_close(y[:, np.newaxis]))

print(np.allclose(y, Y[:, 0]))
print(np.allclose(y, y1))

Y =
 [[11  9 25]
 [25 11  9]
 [ 9 25 11]]
y = Y[:,0] =
 [[11.]
 [25.]
 [ 9.]]
True
True


## Copyright

This tutorial is provided as Open Educational Resource (OER), to be found at
https://github.com/spatialaudio/signals-and-systems-exercises
accompanying the OER lecture
https://github.com/spatialaudio/signals-and-systems-lecture.
Both are licensed under a) the Creative Commons Attribution 4.0 International
License for text and graphics and b) the MIT License for source code.
Please attribute material from the tutorial as *Frank Schultz,
Continuous- and Discrete-Time Signals and Systems - A Tutorial Featuring
Computational Examples, University of Rostock* with
``github URL, commit number and/or version tag, year, (file name and/or content)``.